openapi: 3.0.0
info:
  title: API de Produtos
  version: 1.0.0
  description: Documentação dos endpoints da API de Produtos

servers:
  - url: http://localhost:3000

paths:
  /api/v1/products:
    get:
      tags:
        - Produtos
      summary: Listar todos os produtos
      responses:
        '200':
          description: Lista de produtos
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Big Mac 01
        description:
          type: string
          example: Lorem Ipsum...
        price:
          type: string
          example: "5.00"
        client_id:
          type: string
          example: 67df66d03359ef45ee087872
        category_id:
          type: integer
          example: 1
        original_name:
          type: string
          example: big-mac.png
        stored_filename:
          type: string
          example: product_1_1743853447_big-mac.png
        created_at:
          type: string
          format: date-time
          example: 2025-04-05T11:40:23.000000Z
