#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🔍 Executando Laravel Pint..."
#./vendor/bin/pint

echo "📌 Adicionando arquivos formatados ao commit..."
git add .

echo "✅ Pint finalizado!"

echo "🚀 Executando testes com Pest..."
#./vendor/bin/pest --parallel --stop-on-failure

if [ $? -ne 0 ]; then
  echo "❌ Testes falharam!"
  exit 1
fi

echo "✅ Testes finalizados!"
